INSERT INTO Company (CompanyID, Name, Industry, FundingStage, NumberOfEmployees) VALUES (1, 'Chung, Jones and Paul', 'Cybersecurity', 'Series C', 96);
INSERT INTO Company (CompanyID, Name, Industry, FundingStage, NumberOfEmployees) VALUES (2, 'Austin, Anderson and Hall', 'Cybersecurity', 'Series B', 20);
INSERT INTO Company (CompanyID, Name, Industry, FundingStage, NumberOfEmployees) VALUES (3, 'Roberts, Harper and Henderson', 'Cybersecurity', 'Series C', 432);
INSERT INTO Company (CompanyID, Name, Industry, FundingStage, NumberOfEmployees) VALUES (4, 'Brown-Tran', 'Cybersecurity', 'Series A', 465);
INSERT INTO Company (CompanyID, Name, Industry, FundingStage, NumberOfEmployees) VALUES (5, 'Brewer, Acosta and Guzman', 'Cybersecurity', 'Series A', 387);
INSERT INTO Company (CompanyID, Name, Industry, FundingStage, NumberOfEmployees) VALUES (6, 'Bentley PLC', 'Cybersecurity', 'Seed', 283);
INSERT INTO Company (CompanyID, Name, Industry, FundingStage, NumberOfEmployees) VALUES (7, 'Hardy Ltd', 'Cybersecurity', 'Series A', 278);
INSERT INTO Company (CompanyID, Name, Industry, FundingStage, NumberOfEmployees) VALUES (8, 'Kennedy-Curtis', 'Cybersecurity', 'Series C', 292);
INSERT INTO Company (CompanyID, Name, Industry, FundingStage, NumberOfEmployees) VALUES (9, 'Evans and Sons', 'Cybersecurity', 'Series A', 36);
INSERT INTO Company (CompanyID, Name, Industry, FundingStage, NumberOfEmployees) VALUES (10, 'Williams PLC', 'Cybersecurity', 'Series C', 440);
INSERT INTO Company (CompanyID, Name, Industry, FundingStage, NumberOfEmployees) VALUES (11, 'Smith and Sons', 'Cybersecurity', 'Series C', 28);
INSERT INTO Company (CompanyID, Name, Industry, FundingStage, NumberOfEmployees) VALUES (12, 'Webb and Sons', 'Cybersecurity', 'Seed', 124);
INSERT INTO Company (CompanyID, Name, Industry, FundingStage, NumberOfEmployees) VALUES (13, 'Silva, Oneill and Edwards', 'Cybersecurity', 'Series B', 89);
INSERT INTO Company (CompanyID, Name, Industry, FundingStage, NumberOfEmployees) VALUES (14, 'Sanford PLC', 'Cybersecurity', 'Seed', 305);
INSERT INTO Company (CompanyID, Name, Industry, FundingStage, NumberOfEmployees) VALUES (15, 'Hunt and Sons', 'Cybersecurity', 'Series B', 102);
INSERT INTO Company (CompanyID, Name, Industry, FundingStage, NumberOfEmployees) VALUES (16, 'Johnson, Brown and Berry', 'Cybersecurity', 'Series C', 483);
INSERT INTO Company (CompanyID, Name, Industry, FundingStage, NumberOfEmployees) VALUES (17, 'Nash-Smith', 'Cybersecurity', 'Series B', 368);
INSERT INTO Company (CompanyID, Name, Industry, FundingStage, NumberOfEmployees) VALUES (18, 'Cooley and Sons', 'Cybersecurity', 'Series A', 383);
INSERT INTO Company (CompanyID, Name, Industry, FundingStage, NumberOfEmployees) VALUES (19, 'Roman-Burch', 'Cybersecurity', 'Seed', 220);
INSERT INTO Company (CompanyID, Name, Industry, FundingStage, NumberOfEmployees) VALUES (20, 'Lewis, Griffith and Ward', 'Cybersecurity', 'Series B', 64);
INSERT INTO Company (CompanyID, Name, Industry, FundingStage, NumberOfEmployees) VALUES (21, 'Ward and Sons', 'Cybersecurity', 'Series B', 63);
INSERT INTO Company (CompanyID, Name, Industry, FundingStage, NumberOfEmployees) VALUES (22, 'Bright, Luna and Clark', 'Cybersecurity', 'Series C', 415);
INSERT INTO Company (CompanyID, Name, Industry, FundingStage, NumberOfEmployees) VALUES (23, 'Miller PLC', 'Cybersecurity', 'Series B', 283);
INSERT INTO Company (CompanyID, Name, Industry, FundingStage, NumberOfEmployees) VALUES (24, 'Gardner, Hull and Perkins', 'Cybersecurity', 'Series B', 154);
INSERT INTO Company (CompanyID, Name, Industry, FundingStage, NumberOfEmployees) VALUES (25, 'Bryant, White and Reed', 'Cybersecurity', 'Series C', 76);
INSERT INTO Company (CompanyID, Name, Industry, FundingStage, NumberOfEmployees) VALUES (26, 'Peterson-Marquez', 'Cybersecurity', 'Seed', 173);
INSERT INTO Company (CompanyID, Name, Industry, FundingStage, NumberOfEmployees) VALUES (27, 'Andrews-Hurst', 'Cybersecurity', 'Series C', 124);
INSERT INTO Company (CompanyID, Name, Industry, FundingStage, NumberOfEmployees) VALUES (28, 'Doyle-Serrano', 'Cybersecurity', 'Series C', 296);
INSERT INTO Company (CompanyID, Name, Industry, FundingStage, NumberOfEmployees) VALUES (29, 'Alexander, Burke and Peterson', 'Cybersecurity', 'Seed', 467);
INSERT INTO Company (CompanyID, Name, Industry, FundingStage, NumberOfEmployees) VALUES (30, 'Barrett, Wade and Russell', 'Cybersecurity', 'Series C', 312);
INSERT INTO Company (CompanyID, Name, Industry, FundingStage, NumberOfEmployees) VALUES (31, 'Schultz Inc', 'Cybersecurity', 'Series A', 386);
INSERT INTO Company (CompanyID, Name, Industry, FundingStage, NumberOfEmployees) VALUES (32, 'Rosales-Calderon', 'Cybersecurity', 'Series B', 75);
INSERT INTO Company (CompanyID, Name, Industry, FundingStage, NumberOfEmployees) VALUES (33, 'Taylor Inc', 'Cybersecurity', 'Series A', 468);
INSERT INTO Company (CompanyID, Name, Industry, FundingStage, NumberOfEmployees) VALUES (34, 'Smith-Trevino', 'Cybersecurity', 'Series A', 299);
INSERT INTO Company (CompanyID, Name, Industry, FundingStage, NumberOfEmployees) VALUES (35, 'Morales-Scott', 'Cybersecurity', 'Series C', 474);
INSERT INTO Company (CompanyID, Name, Industry, FundingStage, NumberOfEmployees) VALUES (36, 'Garza-Johnson', 'Cybersecurity', 'Series A', 386);
INSERT INTO Company (CompanyID, Name, Industry, FundingStage, NumberOfEmployees) VALUES (37, 'Clark-Dixon', 'Cybersecurity', 'Series A', 316);
INSERT INTO Company (CompanyID, Name, Industry, FundingStage, NumberOfEmployees) VALUES (38, 'Burton-French', 'Cybersecurity', 'Series A', 282);
INSERT INTO Company (CompanyID, Name, Industry, FundingStage, NumberOfEmployees) VALUES (39, 'Edwards Ltd', 'Cybersecurity', 'Seed', 303);
INSERT INTO Company (CompanyID, Name, Industry, FundingStage, NumberOfEmployees) VALUES (40, 'Murray LLC', 'Cybersecurity', 'Series B', 62);
INSERT INTO Company (CompanyID, Name, Industry, FundingStage, NumberOfEmployees) VALUES (41, 'Chavez, Robles and Meyer', 'Cybersecurity', 'Series A', 257);
INSERT INTO Company (CompanyID, Name, Industry, FundingStage, NumberOfEmployees) VALUES (42, 'Nguyen-Martin', 'Cybersecurity', 'Series C', 494);
INSERT INTO Company (CompanyID, Name, Industry, FundingStage, NumberOfEmployees) VALUES (43, 'Hughes Group', 'Cybersecurity', 'Series B', 259);
INSERT INTO Company (CompanyID, Name, Industry, FundingStage, NumberOfEmployees) VALUES (44, 'Tucker-Evans', 'Cybersecurity', 'Series B', 241);
INSERT INTO Company (CompanyID, Name, Industry, FundingStage, NumberOfEmployees) VALUES (45, 'Patterson-Anderson', 'Cybersecurity', 'Seed', 191);
INSERT INTO Company (CompanyID, Name, Industry, FundingStage, NumberOfEmployees) VALUES (46, 'Holmes, Short and Hill', 'Cybersecurity', 'Series B', 403);
INSERT INTO Company (CompanyID, Name, Industry, FundingStage, NumberOfEmployees) VALUES (47, 'Figueroa-Nolan', 'Cybersecurity', 'Seed', 62);
INSERT INTO Company (CompanyID, Name, Industry, FundingStage, NumberOfEmployees) VALUES (48, 'Blackburn, Parks and Jordan', 'Cybersecurity', 'Series C', 456);
INSERT INTO Company (CompanyID, Name, Industry, FundingStage, NumberOfEmployees) VALUES (49, 'Escobar-Holmes', 'Cybersecurity', 'Series C', 238);
INSERT INTO Company (CompanyID, Name, Industry, FundingStage, NumberOfEmployees) VALUES (50, 'Olson Group', 'Cybersecurity', 'Series C', 242);