INSERT INTO Resource (ResourceID, Type, Description, Availability, CompanyID) VALUES (1, 'Firewall', 'Always safe best. Strong education he church including case practice.', 0, 43);
INSERT INTO Resource (ResourceID, Type, Description, Availability, CompanyID) VALUES (2, 'Antivirus Software', 'Better friend country tell pass. But gun discussion. Fact wear degree never.', 1, 33);
INSERT INTO Resource (ResourceID, Type, Description, Availability, CompanyID) VALUES (3, 'Antivirus Software', 'Anyone impact player sport foot Democrat company water. Over than foreign laugh big send hold.', 0, 27);
INSERT INTO Resource (ResourceID, Type, Description, Availability, CompanyID) VALUES (4, 'Cloud Service', 'Get door tell. Her game win road. Mouth show firm military.', 0, 23);
INSERT INTO Resource (ResourceID, Type, Description, Availability, CompanyID) VALUES (5, 'Cloud Service', 'Water four above show son. Item begin summer yourself investment.', 0, 35);
INSERT INTO Resource (ResourceID, Type, Description, Availability, CompanyID) VALUES (6, 'Antivirus Software', 'Chance notice boy best. Agent fund police. Visit lot quickly feeling.', 1, 25);
INSERT INTO Resource (ResourceID, Type, Description, Availability, CompanyID) VALUES (7, 'Antivirus Software', 'Middle sport go fight music move. Amount I agency executive. Member high share recent beyond data.', 0, 12);
INSERT INTO Resource (ResourceID, Type, Description, Availability, CompanyID) VALUES (8, 'Antivirus Software', 'Investment college religious only along. Anything work early whatever glass simple suddenly stuff.', 0, 36);
INSERT INTO Resource (ResourceID, Type, Description, Availability, CompanyID) VALUES (9, 'Firewall', 'Together apply notice top. Later bring service really church forget cost.', 1, 14);
INSERT INTO Resource (ResourceID, Type, Description, Availability, CompanyID) VALUES (10, 'Cloud Service', 'Either call character way may provide. Ready poor exist.', 1, 7);
INSERT INTO Resource (ResourceID, Type, Description, Availability, CompanyID) VALUES (11, 'Antivirus Software', 'Generation car notice wonder sing drop air. Reflect spend enough worry single.', 0, 29);
INSERT INTO Resource (ResourceID, Type, Description, Availability, CompanyID) VALUES (12, 'Cloud Service', 'Human military agree seem. Listen over fine century responsibility.', 0, 16);
INSERT INTO Resource (ResourceID, Type, Description, Availability, CompanyID) VALUES (13, 'Firewall', 'Pretty six Mr reduce administration help character. Daughter family not impact drive system party.', 0, 11);
INSERT INTO Resource (ResourceID, Type, Description, Availability, CompanyID) VALUES (14, 'Antivirus Software', 'Development maintain interest them measure opportunity wide.', 0, 34);
INSERT INTO Resource (ResourceID, Type, Description, Availability, CompanyID) VALUES (15, 'Firewall', 'Likely one put wait. National wonder upon to. Health as next table impact.', 1, 42);
INSERT INTO Resource (ResourceID, Type, Description, Availability, CompanyID) VALUES (16, 'Cloud Service', 'Above product something have. Morning center over reality significant safe.', 1, 32);
INSERT INTO Resource (ResourceID, Type, Description, Availability, CompanyID) VALUES (17, 'Cloud Service', 'Dark author learn wonder owner try get. Pm include sing drop have.', 0, 21);
INSERT INTO Resource (ResourceID, Type, Description, Availability, CompanyID) VALUES (18, 'Antivirus Software', 'Through buy she play million black. Avoid break appear I why.', 0, 6);
INSERT INTO Resource (ResourceID, Type, Description, Availability, CompanyID) VALUES (19, 'Cloud Service', 'Away design seat. Make role surface. Pay stay degree majority practice treatment should manage.', 0, 26);
INSERT INTO Resource (ResourceID, Type, Description, Availability, CompanyID) VALUES (20, 'Cloud Service', 'Middle last message employee chance reduce believe. Painting arrive peace tonight none.', 1, 3);
INSERT INTO Resource (ResourceID, Type, Description, Availability, CompanyID) VALUES (21, 'Firewall', 'Admit simple listen where. Doctor fly house already season medical.', 0, 42);
INSERT INTO Resource (ResourceID, Type, Description, Availability, CompanyID) VALUES (22, 'Antivirus Software', 'My star trial. Economic north know TV.', 1, 29);
INSERT INTO Resource (ResourceID, Type, Description, Availability, CompanyID) VALUES (23, 'Cloud Service', 'You open computer movement plant yeah create smile. Relationship generation most.', 1, 45);
INSERT INTO Resource (ResourceID, Type, Description, Availability, CompanyID) VALUES (24, 'Antivirus Software', 'Nation month know little yard everyone. Nation appear body great picture learn.', 0, 19);
INSERT INTO Resource (ResourceID, Type, Description, Availability, CompanyID) VALUES (25, 'Firewall', 'Especially single edge ever mission wall. Positive I new wind town either.', 0, 48);
INSERT INTO Resource (ResourceID, Type, Description, Availability, CompanyID) VALUES (26, 'Cloud Service', 'Suggest fight authority total so. Outside also police challenge along.', 0, 42);
INSERT INTO Resource (ResourceID, Type, Description, Availability, CompanyID) VALUES (27, 'Firewall', 'Evidence allow suddenly draw blue. True because situation management see hope PM.', 1, 7);
INSERT INTO Resource (ResourceID, Type, Description, Availability, CompanyID) VALUES (28, 'Firewall', 'Assume price increase sing person measure.', 0, 19);
INSERT INTO Resource (ResourceID, Type, Description, Availability, CompanyID) VALUES (29, 'Antivirus Software', 'Campaign people reflect window. Back today week TV. Learn government before spring night up.', 0, 27);
INSERT INTO Resource (ResourceID, Type, Description, Availability, CompanyID) VALUES (30, 'Cloud Service', 'Lot benefit peace thing. Hold join history south American.', 0, 8);
INSERT INTO Resource (ResourceID, Type, Description, Availability, CompanyID) VALUES (31, 'Firewall', 'Nothing so win garden state full. At physical unit voice top already among.', 0, 13);
INSERT INTO Resource (ResourceID, Type, Description, Availability, CompanyID) VALUES (32, 'Cloud Service', 'Billion keep will learn data follow interest. Move time easy agreement.', 0, 16);
INSERT INTO Resource (ResourceID, Type, Description, Availability, CompanyID) VALUES (33, 'Cloud Service', 'Door window customer strong clear organization whom job.', 0, 29);
INSERT INTO Resource (ResourceID, Type, Description, Availability, CompanyID) VALUES (34, 'Firewall', 'Certainly scientist for discover.', 0, 27);
INSERT INTO Resource (ResourceID, Type, Description, Availability, CompanyID) VALUES (35, 'Firewall', 'Fund capital design. Policy year eat offer eight.', 1, 50);
INSERT INTO Resource (ResourceID, Type, Description, Availability, CompanyID) VALUES (36, 'Firewall', 'Sea general any. Have local pay professional market.', 1, 5);
INSERT INTO Resource (ResourceID, Type, Description, Availability, CompanyID) VALUES (37, 'Firewall', 'Should avoid man sort large. Statement sound require structure sign possible.', 0, 3);
INSERT INTO Resource (ResourceID, Type, Description, Availability, CompanyID) VALUES (38, 'Cloud Service', 'Thing national number. Another end star gas.', 0, 28);
INSERT INTO Resource (ResourceID, Type, Description, Availability, CompanyID) VALUES (39, 'Antivirus Software', 'Director store easy avoid. Music light hard will model my. Lay this clearly enter would eat.', 1, 25);
INSERT INTO Resource (ResourceID, Type, Description, Availability, CompanyID) VALUES (40, 'Cloud Service', 'Sport cultural onto government audience. Beat direction society cup region on far.', 0, 4);
INSERT INTO Resource (ResourceID, Type, Description, Availability, CompanyID) VALUES (41, 'Antivirus Software', 'People could full really him. Modern year administration late difficult husband group end.', 1, 7);
INSERT INTO Resource (ResourceID, Type, Description, Availability, CompanyID) VALUES (42, 'Antivirus Software', 'Improve international organization carry agreement close. Turn card affect while time page.', 1, 28);
INSERT INTO Resource (ResourceID, Type, Description, Availability, CompanyID) VALUES (43, 'Antivirus Software', 'Oil away actually recent.', 0, 13);
INSERT INTO Resource (ResourceID, Type, Description, Availability, CompanyID) VALUES (44, 'Antivirus Software', 'Usually force scientist stop unit. Along senior vote government dinner.', 1, 4);
INSERT INTO Resource (ResourceID, Type, Description, Availability, CompanyID) VALUES (45, 'Firewall', 'Interest yard keep room nation.', 0, 11);
INSERT INTO Resource (ResourceID, Type, Description, Availability, CompanyID) VALUES (46, 'Firewall', 'Them produce treatment much. Paper become perform ability prove child line.', 1, 49);
INSERT INTO Resource (ResourceID, Type, Description, Availability, CompanyID) VALUES (47, 'Cloud Service', 'Soon product thought room boy look nation character. Cell it win treatment their.', 0, 22);
INSERT INTO Resource (ResourceID, Type, Description, Availability, CompanyID) VALUES (48, 'Antivirus Software', 'Though western fly scientist wind important plant thought. Reveal style event.', 0, 29);
INSERT INTO Resource (ResourceID, Type, Description, Availability, CompanyID) VALUES (49, 'Firewall', 'Small well message all. None sell lawyer.', 0, 47);
INSERT INTO Resource (ResourceID, Type, Description, Availability, CompanyID) VALUES (50, 'Firewall', 'Expect begin become what. On subject idea cause open.', 1, 30);